export const PROGRESS_TOKENS = {
  SKILL_PROGRESS_REPOSITORY: Symbol('SKILL_PROGRESS_REPOSITORY'),
  LESSON_SUBMISSION_SERVICE: Symbol('LESSON_SUBMISSION_SERVICE'),
  MASTERY_UPDATE_SERVICE: Symbol('MASTERY_UPDATE_SERVICE'),
  SKILL_PROGRESS_SERVICE: Symbol('SKILL_PROGRESS_SERVICE'),
} as const;

