export const LEADERBOARD_TOKENS = {
  LEAGUE_REPOSITORY: Symbol('LEAGUE_REPOSITORY'),
  PARTICIPANT_REPOSITORY: Symbol('PARTICIPANT_REPOSITORY'),
  USER_TIER_REPOSITORY: Symbol('USER_TIER_REPOSITORY'),
  LEAGUE_HISTORY_REPOSITORY: Symbol('LEAGUE_HISTORY_REPOSITORY'),
} as const;
